title: The website for one cool boy
author: Luca Zhu
email: luca_zhu@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an undergradute studying in Chinese University of Hong Kong in Shenzhen. 
  And my major is computer science. 
theme: mimima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

